name: My First workflow

on:
  push:
    branches: 
      - main
worflow_dispatch

jobs:
  MyFirstJob:
    runs-on: unbuntu-latest

    steps:
      -  run: echo "Hello World!"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name : List files in repository
        run : |
          echo "The repository ${{ github.repository }} contains the following 
        -files:" tree
